# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Bipin Khatiwada
email: mail@erbipin.com
description: > # this means to ignore newlines until "url:"
  Software Developer | Cybersecurity Graduate | A Wanderer of Cosmos.
url:  # the base hostname & protocol for your site
footer_text: Disclaimer - This website stores cookies from Google Analytics to be used for analytics purposes.
baseurl:  # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Open Graph
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
# To achieve this, change serve_og_meta to true and then provide the URL of the
# preview image as the value of og_image.
serve_og_meta: false # Include Open Graph meta tags in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image
# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: bipinkh
twitter_username: bpnkh
linkedin_username: bipinkh
scholar_userid: # your Google Scholar ID
orcid_id: # your ORCID ID
medium_username: # your Medium username
quora_username: # your Quora username
publons_id: # your ID on Publons
research_gate_profile: Bipin_Khatiwada # your profile on ResearchGate
blogger_url: # your blogger URL
upwork_url: https://www.upwork.com/freelancers/~01ecf3081e1704a568
fiverr_url: https://www.fiverr.com/bipin_

contact_note: >
  Email me or drop by on my Twitter or LinkedIn to say hello.

google_analytics: G-WNVRFP9FJ0 # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: blog posts & stories
blog_description: i will soon start writing blogs once i am motivated and have enough time, whenever that will be...

# Pagination
paginate: 4
permalink: /blog/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: erbipin # put your disqus shortname

# Optional features
show_social_icons:  true
enable_anchorjs:    true
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Einstein

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
